# config/config.yaml
defaults:
  - environment: ev_routing
  - agent: dqn_gnn
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

training:
  num_episodes: 2000
  log_interval: 50
  save_interval: 500
  save_path: "ev_dqn_gnn_final.pth"

vehicle:
  battery_capacity_kwh: 60.0
  min_soc_fraction: 0.1
  # --- Energy Model Params (Placeholder values - TUNE THESE) ---
  base_kwh_per_km: 0.18    # Base consumption on flat road, good quality, no congestion
  slope_factor: 0.05       # kwh/km added per degree of positive slope
  congestion_factor: 0.1   # Extra kwh/km added per unit of congestion > 1.0
  speed_factor: 0.0001     # Quadratic penalty factor for speed > 50 kph
  regen_efficiency: 0.6    # Fraction of potential gravitational energy recovered
  stop_penalty_kwh: 0.05   # Energy cost for a stop/start event
  # --- Reward Params ---
  goal_reward: 1000
  fail_penalty_soc: -1000
  fail_penalty_steps: -500
  fail_penalty_invalid: -100
  step_penalty: -1.0       # Cost per step taken
  energy_reward_factor: -1.0 # Multiplier for kWh cost in reward (make it negative)