# config/config.yaml

defaults:
  - override hydra/launcher: basic

environment:
  db_path: "C:\\Users\\YODA\\Documents\\Dhia_Salem_Tutoré_AIM_25-26\\New_repo_clone\\EV-Energy-Optimization\\Graph_Generation\\src\\New_York_network_enhanced_attributes.pkl.gz"
  # Vehicle Parameters (Example values - adjust as needed)
  vehicle_params:
    battery_capacity_kwh: 50.0  # Total capacity of the EV battery
    min_soc_fraction: 0.1       # Minimum required state of charge (10%)
    max_charge_kwh: 40.0        # Max charge per charging stop
    energy_model_params:        # Parameters for the energy calculation in EVRoutingEnv
      base_consumption_rate: 0.2 # kWh/km (base rate)
      slope_factor: 0.05        # Multiplier for slope_deg
      quality_factor: 0.1       # Multiplier for road_quality (lower is better)
      congestion_penalty: 0.1   # Penalty factor for base_congestion

agent:
  device: "cuda" # 'cuda' or 'cpu'
  hidden_dim: 64 # Size of the static embedding and GNN hidden layers
  replay_capacity: 100000
  batch_size: 128
  gamma: 0.99 # Discount factor
  lr: 0.0005  # Learning rate
  target_update_freq: 500 # Steps between updating target network

training:
  num_episodes: 50000
  max_steps_per_episode: 500
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay_steps: 50000 # Number of steps over which epsilon decays
  log_interval: 1000 # Print status every X steps
  save_path: "models/dqn_policy_net.pth"
  checkpoint_interval: 10000 # Save a checkpoint every X episodes
  
  # --- Stage 1 Config ---++
  static_embedding_path: "static_node_embeddings.pt" # Where Stage 1 saves its output
