"""
Configuration Package for Energy Estimation Models.

Contains hyperparameter configurations and settings for all models.
"""

from .energy_features import (
    CATEGORICAL_FEATURES,
    NUMERICAL_FEATURES,
    ALL_FEATURES,
    TARGET_FEATURE
)

from .model_configs import (
    LIGHTGBM_DEFAULT_PARAMS,
    LIGHTGBM_OPTUNA_SPACE,
    LIGHTGBM_OPTIMIZED_PARAMS,
    CATBOOST_DEFAULT_PARAMS,
    CATBOOST_OPTUNA_SPACE,
    CATBOOST_OPTIMIZED_PARAMS,
    XGBOOST_DEFAULT_PARAMS,
    XGBOOST_OPTUNA_SPACE,
    XGBOOST_OPTIMIZED_PARAMS,
    STACKING_DEFAULT_PARAMS,
    STACKING_OPTUNA_SPACE,
    get_model_config
)

from .training_config import (
    DATA_SPLIT_CONFIG,
    PREPROCESSING_CONFIG,
    TRAINING_CONFIG,
    OPTUNA_CONFIG,
    METRICS_CONFIG,
    SAVE_CONFIG,
    CV_CONFIG,
    EARLY_STOPPING_CONFIG,
    LOGGING_CONFIG,
    RESOURCE_CONFIG,
    EXPERIMENT_CONFIG,
    get_training_config,
    update_config
)

__all__ = [
    # Features
    'CATEGORICAL_FEATURES',
    'NUMERICAL_FEATURES',
    'ALL_FEATURES',
    'TARGET_FEATURE',
    
    # Model configs
    'LIGHTGBM_DEFAULT_PARAMS',
    'LIGHTGBM_OPTUNA_SPACE',
    'LIGHTGBM_OPTIMIZED_PARAMS',
    'CATBOOST_DEFAULT_PARAMS',
    'CATBOOST_OPTUNA_SPACE',
    'CATBOOST_OPTIMIZED_PARAMS',
    'XGBOOST_DEFAULT_PARAMS',
    'XGBOOST_OPTUNA_SPACE',
    'XGBOOST_OPTIMIZED_PARAMS',
    'STACKING_DEFAULT_PARAMS',
    'STACKING_OPTUNA_SPACE',
    'get_model_config',
    
    # Training configs
    'DATA_SPLIT_CONFIG',
    'PREPROCESSING_CONFIG',
    'TRAINING_CONFIG',
    'OPTUNA_CONFIG',
    'METRICS_CONFIG',
    'SAVE_CONFIG',
    'CV_CONFIG',
    'EARLY_STOPPING_CONFIG',
    'LOGGING_CONFIG',
    'RESOURCE_CONFIG',
    'EXPERIMENT_CONFIG',
    'get_training_config',
    'update_config'
]
