# config/environment/ev_routing.yaml
name: "EVRoutingEnv"
db_path: "/kaggle/input/tutor/Tutoré/EV-Energy-Optimization/Graph_Generation/src/New_York_network_enhanced_attributes.pkl/New_York_network_enhanced_attributes.pkl" # Path relative to project root
# Add any other environment-specific settings if needed